export const DASHBOARD_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Henry dashboard</title>
<style>
:root{color-scheme:dark;--bg:#101318;--panel:#181d25;--line:#2c3442;--text:#e9edf5;--muted:#9ba7b8;--accent:#8b9cff;--good:#55d69b;--warn:#ffca75;--bad:#ff6b6b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top left,#202a45 0,#101318 36rem);color:var(--text);font:14px/1.5 ui-sans-serif,system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}h1{margin:0;font-size:30px}h2{margin:0 0 12px;font-size:16px}.sub{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.panel{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:14px;padding:16px;box-shadow:0 12px 36px #0003}.wide{grid-column:span 8}.side{grid-column:span 4}.full{grid-column:1/-1}.stat{display:inline-flex;flex-direction:column;margin-right:28px}.stat b{font-size:22px;color:var(--accent)}.stat span{color:var(--muted);font-size:12px}.scroll{max-height:360px;overflow:auto}.row{border-top:1px solid var(--line);padding:10px 0}.row:first-child{border-top:0}.tag{color:var(--accent);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.muted{color:var(--muted)}button{border:1px solid var(--line);background:#242c3a;color:var(--text);padding:8px 12px;border-radius:8px;cursor:pointer}button:hover{border-color:var(--accent)}input,textarea,select{width:100%;background:#0f131a;border:1px solid var(--line);border-radius:8px;color:var(--text);padding:9px;margin:5px 0 8px}textarea{min-height:80px;resize:vertical}.approval{border-left:3px solid var(--warn);padding-left:10px}.ok{color:var(--good)}pre{white-space:pre-wrap;word-break:break-word;color:#c8d2e4;margin:0}.memory-node{font-size:12px;color:var(--muted)}.controls{display:flex;gap:12px;align-items:center}.seg{display:inline-flex;border:1px solid var(--line);border-radius:10px;overflow:hidden}.seg button{border:0;border-radius:0;background:transparent;padding:8px 14px;color:var(--muted)}.seg button.active{background:var(--accent);color:#10131f;font-weight:600}.seg button:hover{border-color:transparent;color:var(--text)}.seg button.active:hover{color:#10131f}
.hero{display:flex;flex-wrap:wrap;align-items:center;gap:22px;margin-bottom:20px;font-variant-numeric:tabular-nums}.hero-item{display:flex;flex-direction:column;gap:2px}.hero-item span{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.06em}.hero-item b{font-size:16px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.pulse-wrap{display:flex;align-items:center;gap:9px}.pulse{width:12px;height:12px;border-radius:50%;background:var(--good);box-shadow:0 0 0 0 color-mix(in srgb,var(--good) 60%,transparent);animation:pulse 2s infinite}.pulse.warn{background:var(--warn);box-shadow:0 0 0 0 color-mix(in srgb,var(--warn) 60%,transparent)}.pulse.critical{background:var(--bad);box-shadow:0 0 0 0 color-mix(in srgb,var(--bad) 60%,transparent)}.pulse.stale{animation-play-state:paused;opacity:.35}@keyframes pulse{0%{box-shadow:0 0 0 0 color-mix(in srgb,currentColor 55%,transparent)}70%{box-shadow:0 0 0 11px transparent}100%{box-shadow:0 0 0 0 transparent}}
.rambar-track{position:relative;height:10px;width:230px;border-radius:6px;background:#0f131a;border:1px solid var(--line);overflow:hidden}.rambar-fill{height:100%;width:0%;background:var(--good);transition:width .5s ease,background-color .5s ease}
.badge{display:inline-block;padding:3px 9px;border-radius:999px;font-size:11px;text-transform:uppercase;letter-spacing:.05em;border:1px solid var(--line);color:var(--muted);width:fit-content}.badge.normal{color:var(--good);border-color:var(--good)}.badge.warn{color:var(--warn);border-color:var(--warn)}.badge.critical{color:var(--bad);border-color:var(--bad)}
#sparkline{display:block;background:#0f131a;border:1px solid var(--line);border-radius:8px}
#graph-wrap{position:relative;width:100%;height:440px;border-radius:10px;overflow:hidden;background:#05070c;border:1px solid var(--line)}#graph-canvas{width:100%;height:100%;display:block}#graph-empty{position:absolute;inset:0;display:none;align-items:center;justify-content:center;color:var(--muted);font-size:13px}.graph-tooltip{position:absolute;pointer-events:none;background:#151a24f0;border:1px solid var(--line);border-radius:8px;padding:8px 10px;font-size:12px;color:var(--text);opacity:0;transform:translate(-50%,-100%);transition:opacity .12s;white-space:nowrap;z-index:5}#graph-note{font-size:11px;margin-top:6px}
@media(max-width:900px){.wide,.side{grid-column:1/-1}}
</style></head><body><main><header><div><h1>🌙 Henry</h1><div class="sub">Luna-orchestrated terminal agent · Dad's control room</div></div><div class="controls"><div class="seg" title="Primary provider"><button id="prov-codex" onclick="setProvider('codex')">Codex</button><button id="prov-claude" onclick="setProvider('claude')">Claude</button></div><button onclick="refresh()">Refresh</button></div></header>
<section class="panel hero" id="hero">
<div class="pulse-wrap"><span class="pulse" id="heartbeat-dot"></span><div class="hero-item"><span>Heartbeat</span><b id="hero-status">connecting…</b></div></div>
<div class="hero-item"><span>Uptime</span><b id="hero-uptime">—</b></div>
<div class="hero-item"><span>Provider</span><b id="hero-provider">—</b></div>
<div class="hero-item"><span>Last activity</span><b id="hero-last-activity">—</b></div>
<div class="hero-item"><span>Pending approvals</span><b id="hero-pending">—</b></div>
<div class="hero-item"><span>Agent-stack RAM · 5.0 GB budget</span><div class="rambar-track"><div class="rambar-fill" id="ram-bar-fill"></div></div><b id="ram-bar-label" style="font-size:11px;color:var(--muted);margin-top:2px">—</b></div>
<div class="hero-item"><span>Memory pressure</span><span class="badge" id="mem-pressure-badge">—</span></div>
<div class="hero-item"><span>RSS · last 60 samples</span><canvas id="sparkline" width="220" height="40"></canvas></div>
</section>
<section class="grid"><div class="panel full" id="status">Loading status…</div>
<div class="panel wide"><h2>Ask Henry</h2><textarea id="prompt" placeholder="What should Henry investigate?"></textarea><button onclick="ask()">Run</button><pre id="answer" style="margin-top:12px"></pre></div>
<div class="panel side"><h2>Dispatch a specialist</h2><select id="role"><option>architect</option><option>runtime</option><option>memory</option><option>dashboard</option><option>gmail</option><option>pr-review</option><option>job-application</option><option>qa</option></select><input id="task" placeholder="Task for the specialist"><button onclick="dispatch()">Dispatch</button><pre id="dispatchResult" style="margin-top:12px"></pre></div>
<div class="panel wide"><h2>Activity</h2><div id="activity" class="scroll"></div></div>
<div class="panel side"><h2>Approval queue</h2><div id="approvals" class="scroll"></div></div>
<div class="panel full"><h2>Job applications</h2><div id="jobstats" style="margin-bottom:10px"></div><div id="jobs" class="scroll"></div></div>
<div class="panel full"><h2>Neural link &middot; memory graph</h2><div id="graph-wrap"><canvas id="graph-canvas"></canvas><div id="graph-tooltip" class="graph-tooltip"></div><div id="graph-empty">memory graph is empty</div></div><div id="graph-note" class="muted"></div></div>
<div class="panel side"><h2>Knowledge base</h2><div id="knowledge"></div></div>
<div class="panel side"><h2>Cover letters</h2><div id="covers" class="scroll"></div></div></section></main>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const r=await fetch(path);return r.json()} async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});return r.json()}
const RAM_BUDGET_BYTES=5*1024*1024*1024;
const rssHistory=[];
const ACTIVITY_LIMIT=80;
function fmtBytes(n){if(n==null||!isFinite(n))return '—';const gb=n/1024/1024/1024;if(gb>=1)return gb.toFixed(2)+' GB';return (n/1024/1024).toFixed(0)+' MB'}
function fmtDuration(sec){if(sec==null||!isFinite(sec))return '—';sec=Math.max(0,Math.round(sec));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;if(h>0)return h+'h '+m+'m';if(m>0)return m+'m '+s+'s';return s+'s'}
function fmtWhen(iso){if(!iso)return '—';try{const d=new Date(iso);const diff=(Date.now()-d.getTime())/1000;if(diff<5)return 'just now';if(diff<60)return Math.floor(diff)+'s ago';if(diff<3600)return Math.floor(diff/60)+'m ago';return d.toLocaleTimeString()}catch{return '—'}}
function activityRow(x){return '<div class="row"><div class="tag">'+esc(x.kind)+'</div><div>'+esc(x.message)+'</div><div class="muted">'+esc(x.timestamp)+'</div></div>'}
function renderActivityList(list){document.querySelector('#activity').innerHTML=(list||[]).map(activityRow).join('')||'<div class="muted">No activity yet.</div>'}
async function loadActivity(){try{const a=await get('/api/activity?limit='+ACTIVITY_LIMIT);renderActivityList(a)}catch{}}
function prependActivity(evt){const el=document.querySelector('#activity');if(el.querySelector('.muted')&&el.children.length===1)el.innerHTML='';el.insertAdjacentHTML('afterbegin',activityRow(evt));while(el.children.length>ACTIVITY_LIMIT)el.removeChild(el.lastElementChild)}
function drawSparkline(){const c=document.querySelector('#sparkline');if(!c||!c.getContext)return;const ctx=c.getContext('2d');const w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(rssHistory.length<2)return;const max=Math.max(RAM_BUDGET_BYTES,...rssHistory);const min=0;ctx.beginPath();rssHistory.forEach((v,i)=>{const x=(i/(rssHistory.length-1))*(w-4)+2;const y=h-2-((v-min)/(max-min||1))*(h-4);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.strokeStyle='#8b9cff';ctx.lineWidth=1.5;ctx.stroke();const last=rssHistory[rssHistory.length-1];const lastX=w-2,lastY=h-2-((last-min)/(max-min||1))*(h-4);ctx.fillStyle='#8b9cff';ctx.beginPath();ctx.arc(lastX,lastY,2,0,Math.PI*2);ctx.fill()}
function setHeartbeatDot(level){const dot=document.querySelector('#heartbeat-dot');dot.classList.remove('warn','critical','stale');if(level==='warn')dot.classList.add('warn');else if(level==='critical')dot.classList.add('critical')}
function renderResources(data){const total=data.totalRssBytes;const pct=Math.min(100,(total/RAM_BUDGET_BYTES)*100);const fill=document.querySelector('#ram-bar-fill');fill.style.width=pct+'%';fill.style.background=pct<60?'var(--good)':pct<85?'var(--warn)':'var(--bad)';document.querySelector('#ram-bar-label').textContent=fmtBytes(total)+' / 5.00 GB';
const mp=data.memoryPressure;const badge=document.querySelector('#mem-pressure-badge');badge.className='badge'+(mp?' '+mp.level:'');badge.textContent=mp?mp.level.toUpperCase()+' · '+mp.freePercent+'% free':'—';
setHeartbeatDot(mp?mp.level:null);
const hb=data.heartbeat||{};document.querySelector('#hero-status').textContent='live';document.querySelector('#hero-uptime').textContent=fmtDuration(hb.uptimeSec);document.querySelector('#hero-last-activity').textContent=fmtWhen(hb.lastActivityAt);document.querySelector('#hero-pending').textContent=hb.pendingApprovals??'—';
rssHistory.push(total);while(rssHistory.length>60)rssHistory.shift();drawSparkline()}
let staleTimer=null;
function armStaleWatch(){if(staleTimer)clearTimeout(staleTimer);staleTimer=setTimeout(()=>{document.querySelector('#heartbeat-dot').classList.add('stale');document.querySelector('#hero-status').textContent='stale'},6000)}
let es=null,fallbackTimer=null;
function startFallbackPolling(){if(fallbackTimer)return;document.querySelector('#hero-status').textContent='polling (SSE unavailable)';fallbackTimer=setInterval(loadActivity,5000)}
function startEvents(){try{es=new EventSource('/api/events')}catch{startFallbackPolling();return}
es.addEventListener('hello',()=>{document.querySelector('#hero-status').textContent='live'});
es.addEventListener('activity',e=>{try{prependActivity(JSON.parse(e.data))}catch{}armStaleWatch()});
es.addEventListener('resources',e=>{try{renderResources(JSON.parse(e.data))}catch{}armStaleWatch()});
es.onerror=()=>{if(es){es.close();es=null}startFallbackPolling()}}
function panelError(id,msg){const el=document.querySelector('#'+id);if(el)el.innerHTML='<div class="muted">'+esc(msg)+'</div>'}
function refreshStatus(){get('/api/status').then(s=>{document.querySelector('#prov-codex').classList.toggle('active',s.provider==='codex');document.querySelector('#prov-claude').classList.toggle('active',s.provider==='claude');document.querySelector('#hero-provider').textContent=esc(s.provider);document.querySelector('#status').innerHTML='<span class="stat"><b>'+esc(s.name)+'</b><span>agent</span></span><span class="stat"><b>'+esc(s.provider)+'</b><span>primary provider</span></span><span class="stat"><b>'+esc(s.approvals)+'</b><span>pending approvals</span></span><span class="stat"><b>'+esc(s.jobs?.readyForReview??0)+'</b><span>jobs to review</span></span><span class="stat"><b>'+esc(s.memory?.memories??0)+'</b><span>memories</span></span><span class="stat"><b class="ok">online</b><span>'+esc(s.dashboard)+'</span></span>'}).catch(()=>panelError('status','status unavailable — retrying…'))}
function refreshApprovals(){get('/api/approvals').then(p=>{document.querySelector('#approvals').innerHTML=(p||[]).map(x=>'<div class="row approval"><div><b>'+esc(x.title)+'</b></div><div class="muted">'+esc(x.status)+' · '+esc(x.recipient||'')+'</div><pre>'+esc(x.body)+'</pre>'+(x.status==='pending'?'<button onclick="approve(\\''+x.id+'\\')">Approve</button>':'' )+(x.status==='approved'?'<button onclick="execute(\\''+x.id+'\\')">Send / post</button>':'')+'</div>').join('')||'<div class="muted">Nothing waiting.</div>'}).catch(()=>panelError('approvals','approvals unavailable'))}
function refreshJobs(){get('/api/jobs').then(j=>{const sm=j.summary||{};document.querySelector('#jobstats').innerHTML='<span class="stat"><b>'+esc(sm.total??0)+'</b><span>total</span></span><span class="stat"><b>'+esc(sm.discovered??0)+'</b><span>discovered</span></span><span class="stat"><b>'+esc(sm.drafted??0)+'</b><span>drafted</span></span><span class="stat"><b>'+esc(sm.readyForReview??0)+'</b><span>ready for review</span></span><span class="stat"><b>'+esc(sm.filled??0)+'</b><span>filled</span></span><span class="stat"><b>'+esc(sm.submitted??0)+'</b><span>submitted</span></span>';document.querySelector('#jobs').innerHTML=(j.applications||[]).map(x=>'<div class="row"><div><b>'+esc(x.posting?.title)+'</b> · '+esc(x.posting?.company)+'</div><div class="muted">'+esc(x.status)+(x.approvalId?' · approval '+esc(x.approvalId):'')+(x.resumePdfPath?' · resume PDF ready':'')+'</div><div class="muted">'+esc(x.posting?.url)+'</div></div>').join('')||'<div class="muted">No job applications yet. Run: henry jobs prepare &lt;url&gt;</div>'}).catch(()=>{panelError('jobstats','—');panelError('jobs','jobs unavailable')})}
function refreshKnowledge(){get('/api/knowledge').then(k=>{document.querySelector('#knowledge').innerHTML=k.error?'<div class="muted">'+esc(k.error)+'</div>':k.loading?'<div class="muted">Loading knowledge base…</div>':(k.stats?'<span class="stat"><b>'+esc(k.stats.count??0)+'</b><span>entries</span></span>'+Object.entries(k.stats.domains||k.stats.tiers||{}).map(([name,n])=>'<span class="stat"><b>'+esc(n)+'</b><span>'+esc(name)+'</span></span>').join(''):'<div class="muted">No knowledge base yet.</div>')}).catch(()=>panelError('knowledge','knowledge unavailable'))}
function refreshCovers(){get('/api/covers').then(c=>{document.querySelector('#covers').innerHTML=(c||[]).map(x=>'<div class="row"><div><b>'+esc(x.name)+'</b></div><div class="muted">'+esc(Math.round((x.size||0)/1024))+' KB · '+esc(new Date(x.mtime).toLocaleString())+'</div></div>').join('')||'<div class="muted">No cover letters yet.</div>'}).catch(()=>panelError('covers','cover letters unavailable'))}
function refresh(){refreshStatus();refreshApprovals();refreshGraph();refreshJobs();refreshKnowledge();refreshCovers()}
async function ask(){const p=document.querySelector('#prompt').value;document.querySelector('#answer').textContent='Henry is thinking…';const r=await post('/api/ask',{prompt:p});document.querySelector('#answer').textContent=r.response||r.error||JSON.stringify(r,null,2);refresh()}
async function dispatch(){const role=document.querySelector('#role').value;const task=document.querySelector('#task').value;document.querySelector('#dispatchResult').textContent='Luna is dispatching…';const r=await post('/api/dispatch',{role,task});document.querySelector('#dispatchResult').textContent=r.response||r.error||JSON.stringify(r,null,2);refresh()}
async function approve(id){await post('/api/approvals/'+encodeURIComponent(id)+'/approve');refresh()} async function execute(id){const r=await post('/api/approvals/'+encodeURIComponent(id)+'/execute');alert(r.result||r.error||'Done');refresh()} async function setProvider(name){const r=await post('/api/settings/provider',{provider:name});if(r.error)alert(r.error);refresh()}

// --- Neural link: force-directed memory graph (vanilla canvas, no libraries) ---
const GRAPH_MAX_NODES=300,GRAPH_FRAME_MS=1000/30,GRAPH_TIER_COLORS={episodic:'#4dd9ff',semantic:'#b98bff',procedural:'#ffbe5c'};
const graphState={nodes:[],edges:[],total:0,width:0,height:0,dpr:1,settled:false,hover:null,pulses:[],lastPulseAt:0,raf:null,lastFrameAt:0};
function graphTierColor(t){return GRAPH_TIER_COLORS[t]||'#8b9cff'}
function graphSizeCanvas(canvas){const wrap=document.querySelector('#graph-wrap');const rect=wrap.getBoundingClientRect();const dpr=window.devicePixelRatio||1;graphState.width=rect.width;graphState.height=rect.height;graphState.dpr=dpr;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr))}
function graphBuild(data){const all=(data.nodes||[]).slice().sort((a,b)=>(b.importance||0)-(a.importance||0));const total=all.length;const nodes=all.slice(0,GRAPH_MAX_NODES);const index={};nodes.forEach((n,i)=>{index[n.id]=i});const w=graphState.width||600,h=graphState.height||440;nodes.forEach(n=>{n.x=w/2+(Math.random()-0.5)*w*0.8;n.y=h/2+(Math.random()-0.5)*h*0.8;n.vx=0;n.vy=0;const imp=n.importance||0,uc=n.useCount||0;n.r=Math.min(26,6+imp*16+Math.log2(uc+1)*2.2)});const edges=(data.edges||[]).filter(e=>index[e.src]!=null&&index[e.dst]!=null).map(e=>({a:index[e.src],b:index[e.dst],weight:e.weight??0.3}));graphState.nodes=nodes;graphState.edges=edges;graphState.total=total;graphState.settled=false;graphState.hover=null;graphState.pulses=[]}
function graphSimulateStep(){const nodes=graphState.nodes,edges=graphState.edges,n=nodes.length;if(!n)return 0;const w=graphState.width,h=graphState.height,cx=w/2,cy=h/2;const REPULSION=1800,SPRING=0.02,SPRING_LEN=70,CENTER=0.0025,DAMPING=0.86;for(let i=0;i<n;i++){const a=nodes[i];let fx=0,fy=0;for(let j=0;j<n;j++){if(i===j)continue;const b=nodes[j];const dx=a.x-b.x,dy=a.y-b.y;const distSq=dx*dx+dy*dy+0.01;const dist=Math.sqrt(distSq);const force=REPULSION/distSq;fx+=(dx/dist)*force;fy+=(dy/dist)*force}fx+=(cx-a.x)*CENTER;fy+=(cy-a.y)*CENTER;a.fx=fx;a.fy=fy}edges.forEach(e=>{const a=nodes[e.a],b=nodes[e.b];if(!a||!b)return;const dx=b.x-a.x,dy=b.y-a.y;const dist=Math.sqrt(dx*dx+dy*dy)||0.01;const stretch=(dist-SPRING_LEN)*SPRING*(0.4+e.weight);const ux=dx/dist,uy=dy/dist;a.fx+=ux*stretch;a.fy+=uy*stretch;b.fx-=ux*stretch;b.fy-=uy*stretch});let maxV=0;nodes.forEach(a=>{a.vx=(a.vx+a.fx)*DAMPING;a.vy=(a.vy+a.fy)*DAMPING;a.x+=a.vx;a.y+=a.vy;a.x=Math.max(a.r,Math.min(w-a.r,a.x));a.y=Math.max(a.r,Math.min(h-a.r,a.y));maxV=Math.max(maxV,Math.abs(a.vx),Math.abs(a.vy))});return maxV}
function graphMaybeSpawnPulse(now){if(!graphState.edges.length)return;if(now-graphState.lastPulseAt<3500+Math.random()*3000)return;graphState.lastPulseAt=now;const e=graphState.edges[Math.floor(Math.random()*graphState.edges.length)];graphState.pulses.push({a:e.a,b:e.b,start:now,dur:900+Math.random()*500})}
function graphDraw(){const canvas=document.querySelector('#graph-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');const dpr=graphState.dpr,w=graphState.width,h=graphState.height;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#05070c';ctx.fillRect(0,0,w,h);const nodes=graphState.nodes,edges=graphState.edges;edges.forEach(e=>{const a=nodes[e.a],b=nodes[e.b];if(!a||!b)return;const hi=graphState.hover!=null&&(e.a===graphState.hover||e.b===graphState.hover);ctx.strokeStyle='rgba(139,156,255,'+(hi?0.85:Math.min(0.35,0.08+e.weight*0.3))+')';ctx.lineWidth=hi?1.6:1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()});const now=performance.now();graphState.pulses=graphState.pulses.filter(p=>now<p.start+p.dur);graphState.pulses.forEach(p=>{const a=nodes[p.a],b=nodes[p.b];if(!a||!b)return;const t=(now-p.start)/p.dur;const x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;const g=ctx.createRadialGradient(x,y,0,x,y,6);g.addColorStop(0,'rgba(214,232,255,0.95)');g.addColorStop(1,'rgba(214,232,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill()});nodes.forEach((nd,idx)=>{const hi=graphState.hover===idx;const color=graphTierColor(nd.tier);const r=nd.r*(hi?1.25:1);const g=ctx.createRadialGradient(nd.x,nd.y,0,nd.x,nd.y,r*2.2);g.addColorStop(0,color);g.addColorStop(0.5,color+'55');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(nd.x,nd.y,r*2.2,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.arc(nd.x,nd.y,hi?r*0.55:r*0.42,0,Math.PI*2);ctx.fill()})}
function graphFrame(){graphState.raf=requestAnimationFrame(graphFrame);const now=performance.now();if(now-graphState.lastFrameAt<GRAPH_FRAME_MS)return;graphState.lastFrameAt=now;if(!graphState.nodes.length)return;if(!graphState.settled){const maxV=graphSimulateStep();if(maxV<0.05)graphState.settled=true}graphMaybeSpawnPulse(now);graphDraw()}
function graphPointerPos(evt,canvas){const rect=canvas.getBoundingClientRect();return {x:evt.clientX-rect.left,y:evt.clientY-rect.top}}
function graphOnMove(evt){const canvas=document.querySelector('#graph-canvas');if(!canvas)return;const pos=graphPointerPos(evt,canvas);const nodes=graphState.nodes;let found=null,best=Infinity;for(let i=0;i<nodes.length;i++){const nd=nodes[i];const dx=nd.x-pos.x,dy=nd.y-pos.y;const d=Math.sqrt(dx*dx+dy*dy);if(d<=nd.r+4&&d<best){found=i;best=d}}graphState.hover=found;const tip=document.querySelector('#graph-tooltip');if(found!=null){const nd=nodes[found];tip.style.opacity='1';tip.style.left=nd.x+'px';tip.style.top=Math.max(0,nd.y-nd.r-8)+'px';tip.innerHTML='<b>'+esc(nd.label||'(memory)')+'</b><br>'+esc(nd.tier||'memory')+' · importance '+esc(typeof nd.importance==='number'?nd.importance.toFixed(2):nd.importance)+' · used '+esc(nd.useCount??0)}else{tip.style.opacity='0'}}
function refreshGraph(){get('/api/memory/graph').then(data=>{graphRender(data)}).catch(()=>{graphState.nodes=[];graphState.edges=[];const empty=document.querySelector('#graph-empty');if(empty){empty.textContent='memory graph unavailable';empty.style.display='flex'}document.querySelector('#graph-note').textContent=''})}
function graphRender(data){const canvas=document.querySelector('#graph-canvas');const empty=document.querySelector('#graph-empty');const note=document.querySelector('#graph-note');if(!canvas)return;const total=(data.nodes||[]).length;if(!total){graphState.nodes=[];graphState.edges=[];note.textContent='';empty.textContent='memory graph is empty';empty.style.display='flex';const ctx=canvas.getContext('2d');ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);return}
empty.style.display='none';graphSizeCanvas(canvas);graphBuild(data);note.textContent=graphState.total>GRAPH_MAX_NODES?('showing top '+GRAPH_MAX_NODES+' of '+graphState.total):'';if(!graphState.raf)graphState.raf=requestAnimationFrame(graphFrame)}
(function graphInit(){const canvas=document.querySelector('#graph-canvas');if(!canvas)return;canvas.addEventListener('mousemove',graphOnMove);canvas.addEventListener('mouseleave',()=>{graphState.hover=null;const tip=document.querySelector('#graph-tooltip');if(tip)tip.style.opacity='0'});let resizeTimer=null;window.addEventListener('resize',()=>{if(!graphState.nodes.length)return;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{graphSizeCanvas(canvas);graphState.settled=false;if(!graphState.raf)graphState.raf=requestAnimationFrame(graphFrame)},150)})})();

refresh();loadActivity();startEvents();armStaleWatch();setInterval(refresh,5000);
</script></body></html>`;
