export const DASHBOARD_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Henry dashboard</title>
<style>
:root{color-scheme:dark;--bg:#101318;--panel:#181d25;--line:#2c3442;--text:#e9edf5;--muted:#9ba7b8;--accent:#8b9cff;--good:#55d69b;--warn:#ffca75}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top left,#202a45 0,#101318 36rem);color:var(--text);font:14px/1.5 ui-sans-serif,system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}h1{margin:0;font-size:30px}h2{margin:0 0 12px;font-size:16px}.sub{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.panel{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:14px;padding:16px;box-shadow:0 12px 36px #0003}.wide{grid-column:span 8}.side{grid-column:span 4}.full{grid-column:1/-1}.stat{display:inline-flex;flex-direction:column;margin-right:28px}.stat b{font-size:22px;color:var(--accent)}.stat span{color:var(--muted);font-size:12px}.scroll{max-height:360px;overflow:auto}.row{border-top:1px solid var(--line);padding:10px 0}.row:first-child{border-top:0}.tag{color:var(--accent);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.muted{color:var(--muted)}button{border:1px solid var(--line);background:#242c3a;color:var(--text);padding:8px 12px;border-radius:8px;cursor:pointer}button:hover{border-color:var(--accent)}input,textarea,select{width:100%;background:#0f131a;border:1px solid var(--line);border-radius:8px;color:var(--text);padding:9px;margin:5px 0 8px}textarea{min-height:80px;resize:vertical}.approval{border-left:3px solid var(--warn);padding-left:10px}.ok{color:var(--good)}pre{white-space:pre-wrap;word-break:break-word;color:#c8d2e4;margin:0}.memory-node{font-size:12px;color:var(--muted)}.controls{display:flex;gap:12px;align-items:center}.seg{display:inline-flex;border:1px solid var(--line);border-radius:10px;overflow:hidden}.seg button{border:0;border-radius:0;background:transparent;padding:8px 14px;color:var(--muted)}.seg button.active{background:var(--accent);color:#10131f;font-weight:600}.seg button:hover{border-color:transparent;color:var(--text)}.seg button.active:hover{color:#10131f}@media(max-width:900px){.wide,.side{grid-column:1/-1}}
</style></head><body><main><header><div><h1>🌙 Henry</h1><div class="sub">Luna-orchestrated terminal agent · Dad's control room</div></div><div class="controls"><div class="seg" title="Primary provider"><button id="prov-codex" onclick="setProvider('codex')">Codex</button><button id="prov-claude" onclick="setProvider('claude')">Claude</button></div><button onclick="refresh()">Refresh</button></div></header>
<section class="grid"><div class="panel full" id="status">Loading status…</div>
<div class="panel wide"><h2>Ask Henry</h2><textarea id="prompt" placeholder="What should Henry investigate?"></textarea><button onclick="ask()">Run</button><pre id="answer" style="margin-top:12px"></pre></div>
<div class="panel side"><h2>Dispatch a specialist</h2><select id="role"><option>architect</option><option>runtime</option><option>memory</option><option>dashboard</option><option>gmail</option><option>pr-review</option><option>job-application</option><option>qa</option></select><input id="task" placeholder="Task for the specialist"><button onclick="dispatch()">Dispatch</button><pre id="dispatchResult" style="margin-top:12px"></pre></div>
<div class="panel wide"><h2>Activity</h2><div id="activity" class="scroll"></div></div>
<div class="panel side"><h2>Approval queue</h2><div id="approvals" class="scroll"></div></div>
<div class="panel full"><h2>Job applications</h2><div id="jobstats" style="margin-bottom:10px"></div><div id="jobs" class="scroll"></div></div>
<div class="panel full"><h2>Engram memory graph</h2><div id="graph" class="scroll"></div></div></section></main>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const r=await fetch(path);return r.json()} async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});return r.json()}
async function refresh(){const [s,a,p,g,j]=await Promise.all([get('/api/status'),get('/api/activity?limit=80'),get('/api/approvals'),get('/api/memory/graph'),get('/api/jobs')]);document.querySelector('#prov-codex').classList.toggle('active',s.provider==='codex');document.querySelector('#prov-claude').classList.toggle('active',s.provider==='claude');document.querySelector('#status').innerHTML='<span class="stat"><b>'+esc(s.name)+'</b><span>agent</span></span><span class="stat"><b>'+esc(s.provider)+'</b><span>primary provider</span></span><span class="stat"><b>'+esc(s.approvals)+'</b><span>pending approvals</span></span><span class="stat"><b>'+esc(s.jobs?.readyForReview??0)+'</b><span>jobs to review</span></span><span class="stat"><b>'+esc(s.memory?.memories??0)+'</b><span>memories</span></span><span class="stat"><b class="ok">online</b><span>'+esc(s.dashboard)+'</span></span>';document.querySelector('#activity').innerHTML=a.map(x=>'<div class="row"><div class="tag">'+esc(x.kind)+'</div><div>'+esc(x.message)+'</div><div class="muted">'+esc(x.timestamp)+'</div></div>').join('')||'<div class="muted">No activity yet.</div>';document.querySelector('#approvals').innerHTML=p.map(x=>'<div class="row approval"><div><b>'+esc(x.title)+'</b></div><div class="muted">'+esc(x.status)+' · '+esc(x.recipient||'')+'</div><pre>'+esc(x.body)+'</pre>'+(x.status==='pending'?'<button onclick="approve(\''+x.id+'\')">Approve</button>':'' )+(x.status==='approved'?'<button onclick="execute(\''+x.id+'\')">Send / post</button>':'')+'</div>').join('')||'<div class="muted">Nothing waiting.</div>';const sm=j.summary||{};document.querySelector('#jobstats').innerHTML='<span class="stat"><b>'+esc(sm.total??0)+'</b><span>total</span></span><span class="stat"><b>'+esc(sm.discovered??0)+'</b><span>discovered</span></span><span class="stat"><b>'+esc(sm.drafted??0)+'</b><span>drafted</span></span><span class="stat"><b>'+esc(sm.readyForReview??0)+'</b><span>ready for review</span></span><span class="stat"><b>'+esc(sm.filled??0)+'</b><span>filled</span></span><span class="stat"><b>'+esc(sm.submitted??0)+'</b><span>submitted</span></span>';document.querySelector('#jobs').innerHTML=(j.applications||[]).map(x=>'<div class="row"><div><b>'+esc(x.posting?.title)+'</b> · '+esc(x.posting?.company)+'</div><div class="muted">'+esc(x.status)+(x.approvalId?' · approval '+esc(x.approvalId):'')+(x.resumePdfPath?' · resume PDF ready':'')+'</div><div class="muted">'+esc(x.posting?.url)+'</div></div>').join('')||'<div class="muted">No job applications yet. Run: henry jobs prepare &lt;url&gt;</div>';document.querySelector('#graph').innerHTML=(g.nodes||[]).slice(0,100).map(n=>'<div class="row memory-node"><b>'+esc(n.label)+'</b><br>'+esc(n.tier||'memory')+' · importance '+esc(n.importance)+' · used '+esc(n.useCount)+'</div>').join('')||'<div class="muted">Engram graph is empty.</div>'}
async function ask(){const p=document.querySelector('#prompt').value;document.querySelector('#answer').textContent='Henry is thinking…';const r=await post('/api/ask',{prompt:p});document.querySelector('#answer').textContent=r.response||r.error||JSON.stringify(r,null,2);refresh()}
async function dispatch(){const role=document.querySelector('#role').value;const task=document.querySelector('#task').value;document.querySelector('#dispatchResult').textContent='Luna is dispatching…';const r=await post('/api/dispatch',{role,task});document.querySelector('#dispatchResult').textContent=r.response||r.error||JSON.stringify(r,null,2);refresh()}
async function approve(id){await post('/api/approvals/'+encodeURIComponent(id)+'/approve');refresh()} async function execute(id){const r=await post('/api/approvals/'+encodeURIComponent(id)+'/execute');alert(r.result||r.error||'Done');refresh()} async function setProvider(name){const r=await post('/api/settings/provider',{provider:name});if(r.error)alert(r.error);refresh()} refresh();setInterval(refresh,5000);
</script></body></html>`;
